### PR TITLE
fix(convert): return error when conversion exceeds f64 bounds

### LINKED ISSUE #1107: to_float and infinity result can crash vector
We ran into an issue where parsing a string with `to_float` exceeds the bounds of `f64::MAX`, which returns a non-error infinity value.
```
$ str_value = "61687855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562"
"61687855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562"

$ parsed_value, err = to_float(str_value)
inf

$ err
null
```
Since `err` was `null`, it's might seem like it's safe to perform operations on this value but subtraction causes vector to panic and crash. This is because `f64::INFINITY - f64::INFINITY == f64::NAN` in rust.
```
$ parsed_value + parsed_value
inf

$ parsed_value + 1
inf

$ parsed_value - 1
inf

$ 1 - parsed_value
-inf

$ parsed_value - parsed_value
thread 'main' panicked at /Users/dan.hable/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ordered-float-4.2.2/src/lib.rs:1331:37:
Subtraction resulted in NaN: FloatIsNan
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I can't find anything in the VRL language, besides using `to_string` to compare with "inf", that would allow me to detect this situation and avoid operations on infinite values. IMHO, I would have expected an error result instead of infinity, similar to how `to_int` behaves.
```
$ parsed_value, err = to_int(str_value)
"function call error for \"to_int\" at (20:29): Invalid integer \"61687855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562855628556285562\": number too large to fit in target type"
```

### PR DESCRIPTION
**Pull request by dhable**
Prior to this commit, string values that would exceed the f64 bounds would return `f64::INFINITY`. This leaks a type into the VRL scripts that could cause a panic without support to check for the value.

Fixes #1107

## Change Type

- [x] Bug fix
- [ ] New feature
- [ ] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?

- [x] Yes
- [ ] No

## Does this PR include user facing changes?

- [x] Yes. Please add a changelog fragment based on
  our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [ ] No. A maintainer will apply the "no-changelog" label to this PR.

## Checklist

- [ ] Our [CONTRIBUTING.md](https://github.com/vectordotdev/vrl/blob/main/CONTRIBUTING.md) is a good starting place.
- [ ] If this PR introduces changes to [LICENSE-3rdparty.csv](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv), please
  run `dd-rust-license-tool write` and commit the changes. More details [here](https://crates.io/crates/dd-rust-license-tool).
- [ ] For new VRL functions, please also create a sibling PR in Vector to document the new function.

### CODE REVIEW

File: changelog.d/1107.fix.md [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Fixes the `to_float` function to return an error instead of "infinity" when parsing a string outside
```
Comment (pront) [inline changelog.d/1107.fix.md:1]: Replace `fix` in the file name with `breaking`.

File: src/compiler/conversion/mod.rs [hunk 2]
```diff
@@ -159,6 +159,11 @@ impl Conversion {
                 let parsed = s
                     .parse::<f64>()
                     .with_context(|_| FloatParseSnafu { s: s.clone() })?;
+                if parsed.is_infinite() {
```
Comment (pront) [inline src/compiler/conversion/mod.rs:162]: This is quite nuanced, but I think the least surprising behavior is to use https://doc.rust-lang.org/std/primitive.f64.html#method.is_normal here.

**Review by pront — COMMENTED** [review]
Thanks @dhable, left a couple of comments but this change makes sense to me. 

Outside of this PR, I will take a look into the `to_float` vs `parse_float` implementations for `string` arguments.

**Comment by pront** [comment]
Hi @dhable, thank you for this contribution. Do you plan to drive this PR to completion? Let me know if I can help.

**Comment by dhable** [comment]
@pront Yes, I just got back from PTO but I'll get the suggestions added.

File: changelog.d/1107.breaking.md [hunk 3]
```diff
@@ -0,0 +1,2 @@
+Fixes the `to_float` function to return an error instead of "infinity" when parsing a string outside
+the f64::MAX / f64::MIN bounds.
```
Comment (pront) [inline changelog.d/1107.breaking.md:2]:
```suggestion
Fixes the `to_float` function to return an error instead of `f64::INFINITY` when parsing [non-normal](https://doc.rust-lang.org/std/primitive.f64.html#method.is_normal) numbers.
```

File: src/compiler/conversion/mod.rs [hunk 4]
```diff
@@ -159,6 +159,11 @@ impl Conversion {
                 let parsed = s
                     .parse::<f64>()
                     .with_context(|_| FloatParseSnafu { s: s.clone() })?;
+                if !parsed.is_normal() {
+                    return Err(Error::NanFloat {
+                        s: format!("Invalid float \"{s}\": number too large to fit in target type"),
```
Comment (pront) [inline src/compiler/conversion/mod.rs:164]:
```suggestion
                        s: format!("Invalid float \"{s}\": not a normal f64 number"),
```

**Review by pront — APPROVED** [review]
Thank you @dhable. Left a couple of suggestions.
