### PR TITLE
fix(parse_groks): catch panic from `onig` on too many match retries

### LINKED ISSUE #15199: Vector panick due to onig regex search error
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector panics when applying a parse_groks transform, due to an unhandled error originating from Onig.

```
Regex search error: retry-limit-in-match over
```

It's quite difficult to precisely identify which of the grok rules or input log is causing the panic since this is happening once every ~ 10 minutes on one server (with a logging rate of approx 10k msg/minutes). 

In the configuration indicated in this issue, you can see the definition of the transform phase causing the panic; and the debug output around the backtrace. 

By trial and error, it seems that this grok rule is much more likely than other to trigger the panic : 

```
"%{TIMESTAMP_ISO8601:log_timestamp} \\| %{LOGLEVEL:log_level}\\s+\\| %{DATA:logger}\\.%{DATA:source}:\\d+ - : opid=%{DATA:opid} :%{GREEDYDATA:log}"
```

This is the structure of the log lines I'm trying to parse : 

```
2022-11-12 08:31:52.197 | DEBUG    | campaignDataFlow.models:perform:124 - : opid=unkown :SVC FOOBARLoader @ http://rtb-dataflow-FOOBAR-prod.traefik.service.consul/FOOBAR_loader?access_token=rtb-FOOBAR-token starting
```
(this is just an exemple, it is not the log line causing the panic)

I can bypass the problem by replacing the rule 
```
%{TIMESTAMP_ISO8601:log_timestamp} \| %{LOGLEVEL:log_level}\s+\| %{DATA:logger}\.%{DATA:source}:\d+ - : opid=%{DATA:opid} :%{GREEDYDATA:log}
```
with 
```
%{TIMESTAMP_ISO8601:log_timestamp} \| %{LOGLEVEL:log_level}\s+\| %{DATA:logger} - : opid=%{DATA:opid} :%{GREEDYDATA:log}
```

After applying the second rule (without the `\.%{DATA:source}:\d+` part, the error did not happen once in 2h. 

### Configuration

```text
[transforms.grokker]
  type = "remap" 
  inputs = ["well_known_formats"] 
  source = '''
  .raw = .message
  new_parsed,err = parse_groks(
    .message,
    patterns:[
      "\\[%{TIMESTAMP_ISO8601:log_timestamp}\\] %{WORD:source}.%{WORD:log_level}: Uncaught PHP Exception %{NOTSPACE:bundle}: %{GREEDYDATA:log}",
      "\\[%{TIMESTAMP_ISO8601:log_timestamp}\\] %{WORD:sourcePhp}.%{WORD:log_level}:%{GREEDYDATA:log}",
      "\\[%{TIMESTAMP_ISO8601:log_timestamp}\\] %{DATA:logger}.%{LOGLEVEL:log_level}: %{GREEDYDATA:log}",
      "\\[%{TIMESTAMP_ISO8601:log_timestamp}.*?\\] \\[\\d+\\] \\[%{LOGLEVEL:log_level}\\] %{GREEDYDATA:log}",
      "\\[%{TIMESTAMP_ISO8601:log_timestamp}.*?\\] \\[\\d+\\] \\[%{LOGLEVEL:log_level}\\] %{GREEDYDATA:log}",
      # python loguru
      "%{TIMESTAMP_ISO8601:log_timestamp} \\| %{LOGLEVEL:log_level}\\s+\\| %{DATA:logger}\\.%{DATA:source}:\\d+ - : opid=%{DATA:opid} :%{GREEDYDATA:log}",
      "%{TIMESTAMP_ISO8601:log_timestamp} \\| %{LOGLEVEL:log_level}\\s+\\| uvicorn:access-log - %{IPORHOST:client}:%{INT:port} - %{WORD:method} %{URIPATH:request}(?:%{URIPARAM:requestparam})? HTTP/%{NUMBER:http_version} %{NUMBER:status}%{DATA:log}",
      "%{TIMESTAMP_ISO8601:log_timestamp} \\| %{LOGLEVEL:log_level}\\s+\\| %{DATA:logger}\\.%{DATA:source}:\\d+ - %{GREEDYDATA:log}",

      # Access log 
      "%{TIMESTAMP_ISO8601:log_timestamp} \\| %{LOGLEVEL:log_level}\\s+\\| uvicorn:access-log - %{IPORHOST:client}:%{INT:port} - %{WORD:method} %{URIPATH:request}(?:%{URIPARAM:requestparam})? HTTP/%{NUMBER:http_version} %{NUMBER:status}",
      "%{TIMESTAMP_ISO8601:log_timestamp} \\| %{LOGLEVEL:log_level}\\s+\\| uvicorn:access-log - %{IPORHOST:client}:%{INT:port} - %{WORD:method} %{URIPATH:request}(?:%{URIPARAM:requestparam})? HTTP/%{NUMBER:http_version} %{NUMBER:status}%{DATA:log}",
      "(?<log_timestamp>\\d{4}-\\d{2}-\\d{2},\\d{2}:\\d{2}:\\d{2}.\\d{3}) \\| %{LOGLEVEL:log_level}\\s+\\| uvicorn:access-log - %{IPORHOST:client}:%{INT:port} - %{WORD:method} %{URIPATH:request}(?:%{URIPARAM:requestparam})? HTTP/%{NUMBER:http_version} %{NUMBER:status}",
      "(?<log_timestamp>\\d{4}-\\d{2}-\\d{2},\\d{2}:\\d{2}:\\d{2}.\\d{3}) \\| %{LOGLEVEL:log_level}\\s+\\| uvicorn:access-log - %{IPORHOST:client}:%{INT:port} - %{WORD:method} %{URIPATH:request}(?:%{URIPARAM:requestparam})? HTTP/%{NUMBER:http_version} %{NUMBER:status}%{DATA:log}",
      "(?<log_timestamp>\\d{4}-\\d{2}-\\d{2},\\d{2}:\\d{2}:\\d{2}.\\d{3}) \\| %{LOGLEVEL:log_level}%{SPACE}\\| uvicorn:access-log - %{IPV4:ip}:%{NUMBER} - %{GREEDYDATA:log}",
      "(?<log_timestamp>\\d{4}-\\d{2}-\\d{2},\\d{2}:\\d{2}:\\d{2}.\\d{3}) \\| %{LOGLEVEL:log_level}%{SPACE}\\| uvicorn:access-log - %{GREEDYDATA:log}",

      # structlog default
      "%{TIMESTAMP_ISO8601:log_timestamp} \\[%{LOGLEVEL:log_level}\\s+\\] %{DATA:log}%{WORD:app}=%{DATA:app} %{GREEDYDATA:kv}"
    ]
    )
  if err==null{
    .vector_parse="grok"
    .parsed=new_parsed
    .parsed.log,err = strip_whitespace(.parsed.log)
    if exists(.parsed.status){
      .parsed.status = to_int!(.parsed.status)
    }
    if exists(.parsed.port){
      .parsed.port = to_int!(.parsed.port)
    }
    if exists(.parsed.log_timestamp){
      del(.parsed.log_timestamp)
    }
    if contains(to_string(.message)??"","access-log"){
      .parsed.log_type = "access-log"
    }
    if exists(.parsed.opid) && (.parsed.opid=="unknown"||.parsed.opid=="unkown"){
      del(.parsed.opid)
    }
    if exists(.parsed.app) && is_array(.parsed.app) && is_array(.parsed.kv){
      push(array(.parsed.kv) ?? [],join(.parsed.app,"=")??{})
    }

  }
  '''
```

### Version

vector 0.25.1 (x86_64-unknown-linux-gnu 9125a99 2022-11-07)

### Debug Output

```text
2022-11-12T06:28:16.112429Z TRACE transform{component_kind="transform" component_id=grokker component_type=remap component_name=grokker}: vector_common::internal_event::events_received: Events received. count=1 byte_size=2091
thread 'vector-worker' panicked at 'Onig: Regex search error: retry-limit-in-match over', /cargo/registry/src/github.com-1ecc6299db9ec823/onig-6.4.0/src/lib.rs:648:23
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: onig::Regex::search_with_encoding
   3: <vrl_compiler::expression::function::FunctionExpressionAdapter<T> as vrl_compiler::expression::Expression>::resolve
2022-11-12T06:28:16.141994Z TRACE source{component_kind="source" component_id=logs component_type=docker_logs component_name=logs}: vector_common::internal_event::bytes_received: Bytes received. byte_size=115 protocol=http
2022-11-12T06:28:16.142023Z TRACE source{component_kind="source" component_id=logs component_type=docker_logs component_name=logs}: vector::internal_events::docker_logs: Events received. count=1 byte_size=1778 container_id=54b82a4a8b4d14aebde08dd392392ea9a430136a3620f0a7d86d69f898d8d1a7
   4: <vrl_compiler::expression::function_call::FunctionCall as vrl_compiler::expression::Expression>::resolve
   5: <vrl_compiler::2022-11-12T06:28:16.142047Z TRACE source{component_kind="source" component_id=logs component_type=docker_logs component_name=logs}: vector_buffers::topology::channel::limited_queue: Sent item.
expression::Expr as vrl_compiler::2022-11-12T06:28:16.142051Z TRACE source{component_kind="source" component_id=logs component_type=docker_logs component_name=logs}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=1890 output=_default
expression::Expression>::resolve
   6: <vrl_compiler::expression::Expr as vrl_compiler::expression::Expression>::resolve
2022-11-12T06:28:16.142066Z TRACE source{component_kind="source" component_id=logs component_type=docker_logs component_name=logs}: vector_buffers::topology::channel::limited_queue: Sent item.
2022-11-12T06:28:16.142071Z TRACE source{component_kind="source" component_id=logs component_type=docker_logs component_name=logs}: vector_core::fanout: Sent item to fanout.
2022-11-12T06:28:16.142078Z TRACE transform{component_kind="transform" component_id=stripper component_type=remap component_name=stripper}: vector_common::internal_event::events_received: Events received. count=1 byte_size=1890
2022-11-12T06:28:16.142116Z TRACE transform{component_kind="transform" component_id=stripper component_type=remap component_name=stripper}: vector_buffers::topology::channel::limited_queue: Sent item.
2022-11-12T06:28:16.142119Z TRACE transform{component_kind="transform" component_id=stripper component_type=remap component_name=stripper}: vector_core::fanout: Sent item to fanout.
2022-11-12T06:28:16.142121Z TRACE transform{component_kind="transform" component_id=stripper component_type=remap component_name=stripper}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=2064 output=_default
2022-11-12T06:28:16.142128Z TRACE transform{component_kind="transform" component_id=well_known_formats component_type=remap component_name=well_known_formats}: vector_common::internal_event::events_received: Events received. count=1 byte_size=2040
   7: <vrl_compiler::expression::block::Block as vrl_compiler::expression::Expression>::resolve
2022-11-12T06:28:16.142169Z TRACE transform{component_kind="transform" component_id=well_known_formats component_type=remap component_name=well_known_formats}: vector_buffers::topology::channel::limited_queue: Sent item.
2022-11-12T06:28:16.142173Z TRACE transform{component_kind="transform" component_id=well_known_formats component_type=remap component_name=well_known_formats}: vector_core::fanout: Sent item to fanout.
2022-11-12T06:28:16.142175Z TRACE transform{component_kind="transform" component_id=well_known_formats component_type=remap component_name=well_known_formats}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=2064 output=_default
2022-11-12T06:28:16.142181Z TRACE transform{component_kind="transform" component_id=grokker component_type=remap component_name=grokker}: vector_common::internal_event::events_received: Events received. count=1 byte_size=2040
   8: vrl::runtime::Runtime::resolve
   9: <vector::transforms::remap::Remap<Runner> as vector_core::transform::SyncTransform>::transform
  10: vector_core::transform::SyncTransform::transform_all
  11: tokio::runtime::task::core::CoreStage<T>::poll
  12: tokio::runtime::task::raw::poll
  13: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  14: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'vector-worker' panicked at 'internal error: entered unreachable code: join error or bad poll', src/topology/builder.rs:764:30
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: vector::topology::builder::Runner::run_concurrently::{{closure}}
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: tokio::runtime::task::core::CoreStage<T>::poll
   6: tokio::runtime::task::raw::poll
   7: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   8: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2022-11-12T06:28:16.143264Z ERROR transform{component_kind="transform" component_id=grokker component_type=remap component_name=grokker}: vector::topology: An error occurred that Vector couldn't handle: the task panicked and was aborted.
2022-11-12T06:28:16.143280Z  INFO vector: Vector has stopped.
2022-11-12T06:28:16.143343Z  INFO source{component_kind="source" component_id=logs component_type=docker_logs component_name=logs}: vector::internal_events::docker_logs: Stopped watching for container logs. container_id=2e8406588c1f98a78be4ad7f73754d5411ec74f837952b3194469661ebe8dc67
```

### Example Data

2022-11-12 08:31:52.197 | DEBUG    | campaignDataFlow.models:perform:124 - : opid=unkown :SVC FOOBARLoader @ http://rtb-dataflow-FOOBAR-prod.traefik.service.consul/FOOBAR_loader?access_token=rtb-FOOBAR-token starting

### Additional Context

Vector is running directly on the host machine. 

### References

* #11076

### PR DESCRIPTION
**Pull request by tessneau**
fixes [#15199](https://github.com/vectordotdev/vector/issues/15199) 

Since the panic is coming from `rust-onig` and for which an issue was opened [here](https://github.com/rust-onig/rust-onig/issues/178), this aims to achieve a short term fix of catching the panic and handling it as a custom error

### CODE REVIEW

**Review by bruceg — APPROVED** [review]

**Review by vladimir-dd — APPROVED** [review]

File: src/datadog/grok/parse_grok.rs [hunk 1]
```diff
@@ -416,6 +420,24 @@ mod tests {
...
+            ],
+            BTreeMap::new()
+        ).expect("couldn't parse rules");
+
+        let parsed = parse_grok(
```
Comment (pront) [inline src/datadog/grok/parse_grok.rs:433]: Nit: this scary text could live under a `parse_grok` directory in https://github.com/vectordotdev/vrl/tree/main/tests/data/fixtures. Same for the pattern above.

File: src/datadog/grok/parse_grok.rs [hunk 2]
```diff
@@ -32,23 +33,25 @@ pub fn parse_grok(source_field: &str, grok_rules: &[GrokRule]) -> Result<Value,
 /// Possible errors:
```
Comment (pront) [inline src/datadog/grok/parse_grok.rs:33]: Nit:
```suggestion
///
/// # Errors
///
```

File: src/datadog/grok/grok.rs [hunk 3]
```diff
@@ -107,10 +110,20 @@ impl Pattern {
...
+        &'a self,
+        text: &'a str,
+    ) -> Result<Option<Matches<'a>>, GrokRuntimeError> {
+        let result = panic::catch_unwind(|| self.regex.captures(text));
+
+        match result {
+            Ok(Some(cap)) => Ok(Some(Matches::new(cap, &self.names))),
+            Ok(None) => Ok(None),
+            // https://github.com/rust-onig/rust-onig/issues/178
+            Err(_) => Err(GrokRuntimeError::FailedToMatch(
```
Comment (pront) [inline src/datadog/grok/grok.rs:123]: Notes:
* This will match all panics but this block assumes it's always due to https://github.com/rust-onig/rust-onig/issues/178. 
* However, handling the `Err` payload is problematic ⚠️ , see last paragraph https://doc.rust-lang.org/std/panic/fn.catch_unwind.html#notes.
* I think this will work as is but flagging this for awareness.

**Review by pront — APPROVED** [review]

File: src/datadog/grok/parse_grok.rs (hunk 2 above)
Comment (tessneau) [reply src/datadog/grok/parse_grok.rs]: https://github.com/vectordotdev/vrl/pull/1079/commits/de23c953c1e4c659757730c5003ad8a05d78c4ab

File: src/datadog/grok/parse_grok.rs (hunk 1 above)
Comment (tessneau) [reply src/datadog/grok/parse_grok.rs:438]: good idea ! https://github.com/vectordotdev/vrl/pull/1079/commits/b3727585c449a0da95d66e9b65f2c3ec3f3bf998

File: src/datadog/grok/grok.rs (hunk 3 above)
Comment (tessneau) [reply src/datadog/grok/grok.rs:123]: that's a good point, I've made the error message less specific for the time being: https://github.com/vectordotdev/vrl/pull/1079/commits/3acf0d08bac697b33331fe4151189060fbc90c94 

since the panic still gets printed to console, users should hopefully have enough indication of what went wrong e.g. for this issue the panic would show 
```
Regex search error: retry-limit-in-match over
```

**Review by pront — APPROVED** [review]
Looks good 👍
