### PR TITLE
(fix stdlib): Fix `validate_json_schema` to prevent compile-time panics

### LINKED ISSUE #1474: `validate_json_schema` - Missing JSON schema file causes panic
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Problem

The implementation of `validate_json_schema` requires that the referenced JSON schema file be accessible _at function call compile time_, rather than merely at runtime / evaluation time. If the given JSON schema file path is inaccessible, VRL and Vector will panic, causing a total app crash.

I believe the intention would be to merely throw a VRL function error at runtime.

### VRL Program

```text
valid, err = validate_json_schema(s'{"hi":1}', "some/bad/path/json-schema.json")
```

### VRL and/or Vector Version

VRL 0.26 in Vector 0.49

### Debug Output

```text
$ valid, err = validate_json_schema(s'{"hi":1}', "some/bad/path/json-schema.json")
thread 'main' panicked at src/stdlib/validate_json_schema.rs:83:56:
JSON schema not found: "Failed to open schema definition file 'some/bad/path/json-schema.json': No such file or directory (os error 2)"
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/result.rs:1732:5
   3: core::result::Result<T,E>::expect
             at /home/sbalmos/.rustup/toolchains/1.88-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1089:23
   4: <vrl::stdlib::validate_json_schema::ValidateJsonSchema as vrl::compiler::function::Function>::compile
             at ./src/stdlib/validate_json_schema.rs:83:13
   5: vrl::compiler::expression::function_call::Builder::compile
             at ./src/compiler/expression/function_call.rs:419:20
   6: vrl::compiler::compiler::Compiler::compile_function_call::{{closure}}
             at ./src/compiler/compiler.rs:741:13
   7: core::option::Option<T>::and_then
             at /home/sbalmos/.rustup/toolchains/1.88-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1477:24
   8: vrl::compiler::compiler::Compiler::compile_function_call
             at ./src/compiler/compiler.rs:713:29
   9: vrl::compiler::compiler::Compiler::compile_expr
             at ./src/compiler/compiler.rs:179:35
  10: vrl::compiler::compiler::Compiler::compile_assignment
             at ./src/compiler/compiler.rs:525:36
  11: vrl::compiler::compiler::Compiler::compile_expr
             at ./src/compiler/compiler.rs:177:33
  12: vrl::compiler::compiler::Compiler::compile_root_exprs
             at ./src/compiler/compiler.rs:287:41
  13: vrl::compiler::compiler::Compiler::compile
             at ./src/compiler/compiler.rs:120:27
  14: vrl::compiler::compile_with_state
             at ./src/compiler/mod.rs:142:18
  15: vrl::cli::repl::resolve
             at ./src/cli/repl.rs:172:25
  16: <vrl::cli::repl::Repl as rustyline::validate::Validator>::validate
             at ./src/cli/repl.rs:304:22
  17: rustyline::edit::State<H>::validate
             at /home/sbalmos/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustyline-16.0.0/src/edit.rs:240:26
  18: rustyline::command::execute
             at /home/sbalmos/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustyline-16.0.0/src/command.rs:133:37
  19: rustyline::Editor<H,I>::readline_edit
             at /home/sbalmos/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustyline-16.0.0/src/lib.rs:784:19
  20: rustyline::Editor<H,I>::readline_with
             at /home/sbalmos/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustyline-16.0.0/src/lib.rs:664:30
  21: rustyline::Editor<H,I>::readline
             at /home/sbalmos/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustyline-16.0.0/src/lib.rs:638:9
  22: vrl::cli::repl::run
             at ./src/cli/repl.rs:76:24
  23: vrl::cli::cmd::repl
             at ./src/cli/cmd.rs:206:5
  24: vrl::cli::cmd::run
             at ./src/cli/cmd.rs:126:9
  25: vrl::cli::cmd::cmd
             at ./src/cli/cmd.rs:102:11
  26: vrl::main
             at ./lib/cli/src/main.rs:5:24
  27: core::ops::function::FnOnce::call_once
             at /home/sbalmos/.rustup/toolchains/1.88-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101
```

### Example

_No response_

### Additional Context

The issue(s) seem to lie in that the check for a valid path is during the `compile` phase of the `ValidateJsonSchema` `Function` impl, at https://github.com/vectordotdev/vrl/blob/main/src/stdlib/validate_json_schema.rs#L81-L83. This call to `get_json_schema_definition` should probably be moved into the runtime evaluation phase, in the `resolve` `FunctionExpression` impl of `ValidateSchemaJsonFn`, and return an Error if the schema cannot be loaded.

### References

_No response_

### PR DESCRIPTION
**Pull request by sbalmos**
## Summary

This PR fixes the issue noted in #1474, where VRL (and thus Vector) panics if the referenced JSON schema file path is not accessible at function compile-time. This PR moves the loading of the schema file to the first runtime evaluation of the function. This better aligns the expectation that VRL and Vector won't fully crash, but will merely throw a standard VRL function call error, if the JSON schema file cannot be accessed.

## Change Type

- [x] Bug fix
- [ ] New feature
- [ ] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?

- [X] Yes
- [ ] No

## Does this PR include user facing changes?

- [x] Yes. Please add a changelog fragment based on
  our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [ ] No. A maintainer will apply the "no-changelog" label to this PR.

## Checklist

- [ ] Our [CONTRIBUTING.md](https://github.com/vectordotdev/vrl/blob/main/CONTRIBUTING.md) is a good starting place.
- [ ] If this PR introduces changes to [LICENSE-3rdparty.csv](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv), please
  run `dd-rust-license-tool write` and commit the changes. More details [here](https://crates.io/crates/dd-rust-license-tool).
- [ ] For new VRL functions, please also create a sibling PR in Vector to document the new function.

## References

- Closes: #1474

### CODE REVIEW

File: src/stdlib/validate_json_schema.rs [hunk 1]
```diff
@@ -138,7 +133,7 @@ mod non_wasm {
 
             // Quick empty check
             if bytes.is_empty() {
-                return Ok(value!(false)); // Empty JSON is typically invalid
+                return Err(ExpressionError::from("Empty JSON value")); // Empty JSON is typically invalid
```
Comment (pront) [inline src/stdlib/validate_json_schema.rs]: "typically invalid" - does it ever result in a valid schema?

**Review by pront — COMMENTED** [review]
Hi @sbalmos, the panic fix is great. Can you submit it as a separate PR please? 

Regarding the other change, it is a breaking change. I also realized that it is awkward to return `true` for valid but error for invalid JSON values.

We either need a `conforms_to_schema` that returns a bool or what we have now but return a `Result<()>`. I guess we have to go with the latter for this function. But I would also like to hear your thoughts on this. Thanks!

File: src/stdlib/validate_json_schema.rs (hunk 1 above)
Comment (sbalmos) [reply src/stdlib/validate_json_schema.rs]: In fact a null body is invalid JSON. But this comment predated the PR, so I wasn't going to change it :)

**Review by pront — APPROVED** [review]
Thanks!

**Comment by pront** [comment]
>  I think it's more straightforward to return `Result<()>` at this point. Building a whole separate function would be awkward and confusing - what would the new function do that `validate_json_schema` shouldn't? The functionality difference probably wouldn't be obvious based on function name. And then also we'd have to separate the JSON schema compilation and caching into shared code between the two functions, etc etc etc. It'll be cleaner just to fix up `validate_json_schema`'s return.

Agreed

File: changelog.d/1476.fix.md [hunk 2]
```diff
@@ -0,0 +1 @@
+This fixes the `validate_json_schema` function behavior to not panic if the JSON schema file cannot be accessed or is invalid.
```
Comment (pront) [inline changelog.d/1476.fix.md]:
```suggestion
The `validate_json_schema` function no longer panics if the JSON schema file cannot be accessed or is invalid.
```
