### PR TITLE
fix(timestamp conversion): use `timestamp_nanos_opt` to avoid panics

### LINKED ISSUE #978: Vector stops with panic at to_unix_timestamp format:nanoseconds VRL function
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector panics at timestamp conversation to_unix_timestamp and crashes. Log messages:

```
vector[582913]: thread 'vector-worker' panicked at 'value can not be represented in a timestamp with nanosecond precision.', /cargo/registry/src/index.crates>
vector[582913]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ox2-vctr-srv01 vector[582913]: thread 'vector-worker' panicked at 'internal error: entered unreachable code: join error or bad poll', src/topology/builder.rs:890:30
ERROR transform{component_kind="transform" component_id=check_unix_timestamp component_type=remap component_n
INFO vector: Vector has stopped.
```

We found out that it was a very small date in some of the logs. This one message has crashed all our 3 aggregators. How: we have Kafka between agents and aggregators, one message crashed first vector and was not consumed, then other two after rebalancing tried to consume this message and also crashed. All 3 aggregators were continuously restarting every 10 seconds, until our fix in VRL.

### Configuration

```text
Vector 0.33.1 
Streaming model (agent - kafka -aggregators)

if exists(.ts) {
      timestampTs , err = parse_timestamp(del(.ts), "%+")
      if err != null {
          .err = err
      } else {
         .Timestamp = to_unix_timestamp(timestampTs, "nanoseconds")
      }
    }
```

### Version

0.33.1

### Debug Output

_No response_

### Example Data

Input: 
"ts": "1677-09-21 00:12:43.145224192Z" - OK. [VRL Playground](https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiXG4gICAgaWYgZXhpc3RzKC50cykge1xuICAgICAgdGltZXN0YW1wVHMgLCBlcnIgPSBwYXJzZV90aW1lc3RhbXAoZGVsKC50cyksIFwiJStcIilcbiAgICAgIGlmIGVyciAhPSBudWxsIHtcbiAgICAgICAgICAuZXJyID0gZXJyXG4gICAgICB9IGVsc2Uge1xuICAgICAgICAgICMgaXQgb3ZlcmZsb3dzIHdoZW4gbmFub3NlY29uZHMgaXMgdmVyeSBzbWFsbCBvciBpbnZhbGlkIGRhdGUgXG4gICAgICAgICAgIyBUYWtlIGEgbG9vayBhdCBCcm93c2VyIENvbnNvbGUgXG4gICAgICAgICAgIyAxNjc3LTA5LTIxIDAwOjEyOjQzLjE0NTIyNDE5MlogLT4gLTkyMjMzNzIwMzY4NTQ3NzYwMDAgT0tcbiAgICAgICAgICAjIDE2NzctMDktMjEgMDA6MTI6NDMuMTQ1MjI0MTkxWiAtPiBhbiBlcnJvciBVbmNhdWdodCBSdW50aW1lRXJyb3I6IHVucmVhY2hhYmxlIChwYW5pYylcbiAgICAgICAgICAjIDAwMDAtMDktMjEgMDA6MTI6NDMuMTQ1MjI0MTkxWiAtPiBhbiBlcnJvciBVbmNhdWdodCBSdW50aW1lRXJyb3I6IHVucmVhY2hhYmxlIChwYW5pYylcbiAgICAgICAgICAjIFxuICAgICAgICAgLlRpbWVzdGFtcCA9IHRvX3VuaXhfdGltZXN0YW1wKHRpbWVzdGFtcFRzLCBcIm5hbm9zZWNvbmRzXCIpXG4gICAgICB9XG4gICAgfVxuIiwiZXZlbnQiOnsidHMiOiIxNjc3LTA5LTIxIDAwOjEyOjQzLjE0NTIyNDE5MloifSwiaXNfanNvbmwiOmZhbHNlLCJlcnJvciI6bnVsbH0%3D)
"ts": "1677-09-21 00:12:43.145224191Z" - Fail. thread 'vector-worker' panicked at 'value can not be represented in a timestamp with nanosecond precision.' [VRL Playground](https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiXG4gICAgaWYgZXhpc3RzKC50cykge1xuICAgICAgdGltZXN0YW1wVHMgLCBlcnIgPSBwYXJzZV90aW1lc3RhbXAoZGVsKC50cyksIFwiJStcIilcbiAgICAgIGlmIGVyciAhPSBudWxsIHtcbiAgICAgICAgICAuZXJyID0gZXJyXG4gICAgICB9IGVsc2Uge1xuICAgICAgICAgICMgaXQgb3ZlcmZsb3dzIHdoZW4gbmFub3NlY29uZHMgaXMgdmVyeSBzbWFsbCBvciBpbnZhbGlkIGRhdGUgXG4gICAgICAgICAgIyBUYWtlIGEgbG9vayBhdCBCcm93c2VyIENvbnNvbGUgXG4gICAgICAgICAgIyAxNjc3LTA5LTIxIDAwOjEyOjQzLjE0NTIyNDE5MlogLT4gLTkyMjMzNzIwMzY4NTQ3NzYwMDAgT0tcbiAgICAgICAgICAjIDE2NzctMDktMjEgMDA6MTI6NDMuMTQ1MjI0MTkxWiAtPiBhbiBlcnJvciBVbmNhdWdodCBSdW50aW1lRXJyb3I6IHVucmVhY2hhYmxlIChwYW5pYylcbiAgICAgICAgICAjIDAwMDAtMDktMjEgMDA6MTI6NDMuMTQ1MjI0MTkxWiAtPiBhbiBlcnJvciBVbmNhdWdodCBSdW50aW1lRXJyb3I6IHVucmVhY2hhYmxlIChwYW5pYylcbiAgICAgICAgICAjIFxuICAgICAgICAgLlRpbWVzdGFtcCA9IHRvX3VuaXhfdGltZXN0YW1wKHRpbWVzdGFtcFRzLCBcIm5hbm9zZWNvbmRzXCIpXG4gICAgICB9XG4gICAgfVxuIiwiZXZlbnQiOnsidHMiOiIxNjc3LTA5LTIxIDAwOjEyOjQzLjE0NTIyNDE5MVoifSwiaXNfanNvbmwiOmZhbHNlLCJlcnJvciI6bnVsbH0%3D)
"ts": "0000-09-21 00:12:43.145224192Z"  - Fail. thread 'vector-worker' panicked at 'value can not be represented in a timestamp with nanosecond precision.' [VRL Playground](https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiXG4gICAgaWYgZXhpc3RzKC50cykge1xuICAgICAgdGltZXN0YW1wVHMgLCBlcnIgPSBwYXJzZV90aW1lc3RhbXAoZGVsKC50cyksIFwiJStcIilcbiAgICAgIGlmIGVyciAhPSBudWxsIHtcbiAgICAgICAgICAuZXJyID0gZXJyXG4gICAgICB9IGVsc2Uge1xuICAgICAgICAgICMgaXQgb3ZlcmZsb3dzIHdoZW4gbmFub3NlY29uZHMgaXMgdmVyeSBzbWFsbCBvciBpbnZhbGlkIGRhdGUgXG4gICAgICAgICAgIyBUYWtlIGEgbG9vayBhdCBCcm93c2VyIENvbnNvbGUgXG4gICAgICAgICAgIyAxNjc3LTA5LTIxIDAwOjEyOjQzLjE0NTIyNDE5MlogLT4gLTkyMjMzNzIwMzY4NTQ3NzYwMDAgT0tcbiAgICAgICAgICAjIDE2NzctMDktMjEgMDA6MTI6NDMuMTQ1MjI0MTkxWiAtPiBhbiBlcnJvciBVbmNhdWdodCBSdW50aW1lRXJyb3I6IHVucmVhY2hhYmxlIChwYW5pYylcbiAgICAgICAgICAjIDAwMDAtMDktMjEgMDA6MTI6NDMuMTQ1MjI0MTkxWiAtPiBhbiBlcnJvciBVbmNhdWdodCBSdW50aW1lRXJyb3I6IHVucmVhY2hhYmxlIChwYW5pYylcbiAgICAgICAgICAjIFxuICAgICAgICAgLlRpbWVzdGFtcCA9IHRvX3VuaXhfdGltZXN0YW1wKHRpbWVzdGFtcFRzLCBcIm5hbm9zZWNvbmRzXCIpXG4gICAgICB9XG4gICAgfVxuIiwiZXZlbnQiOnsidHMiOiIwMDAwLTA5LTIxIDAwOjEyOjQzLjE0NTIyNDE5MVoifSwiaXNfanNvbmwiOmZhbHNlLCJlcnJvciI6bnVsbH0%3D)

Reproduced in VRL Playground
изображение

### Additional Context

_No response_

### References

https://github.com/vectordotdev/vrl/blob/16889935bf08268547dd494054dc906705a1dfc7/src/stdlib/to_unix_timestamp.rs#L4
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by pront**
closes: https://github.com/vectordotdev/vrl/issues/978

### CODE REVIEW

File: changelog.d/979.fix.md [hunk 1]
```diff
@@ -0,0 +1 @@
+Replaced all usages of `timestamp_nanos` with `timestamp_nanos_opt` to avoid panics when the timestamp is out of range.
```
Comment (jszwedko) [inline changelog.d/979.fix.md:1]:
```suggestion
`to_unix_timestamp`, `to_float`, and `uuid_v7` can now return an error if the supplied timestamp is unrepresentable as a nanosecond timestamp. Previously the function calls would panic.
```

The changelogs should have the user in mind as the audience. I also think this is a breaking change, no? We'll want to document how to migrate.

**Review by jszwedko — COMMENTED** [review]
I think this is a breaking change, no? I think the fallibility of these functions needs to be updated. We'll also want to document how to migrate.

Nit: I think we could use clippy to disallow calls to `timestamp_nanos()` to avoid accidentally introducing a panic in the future. See https://rust-lang.github.io/rust-clippy/master/#/disallowed_method

File: changelog.d/979.fix.md (hunk 1 above)
Comment (pront) [reply changelog.d/979.fix.md:1]: Right, marking this PR as a draft for now. I will try to find some propose a migration plan. I need to refresh my memory on the deprecation process as well.

Comment (r3code) [reply changelog.d/979.fix.md:1]: We provide linters for such changes. In this way we have eliminated the deprecation of to_timestamp. 
I think there is no problem in this case, because the vector during validation will report that to_unix_timestamp returns an error, and this is not handled

Comment (r3code) [reply changelog.d/979.fix.md:1]: Any plans to release the fix?

Comment (pront) [reply changelog.d/979.fix.md]: In this case, we would have to document that to_unix_timestamp (and uuid_v7) are now fallible. And then users would have to update the VRL source in their configs when updating their Vector version.

File: changelog.d/979.fix.md [hunk 2]
```diff
@@ -0,0 +1 @@
+`to_unix_timestamp`, `to_float`, and `uuid_v7` can now return an error if the supplied timestamp is unrepresentable as a nanosecond timestamp. Previously the function calls would panic.
```
Comment (jszwedko) [inline changelog.d/979.fix.md:1]: Should this file be `.breaking.`?

Comment (pront) [reply changelog.d/979.fix.md:1]: Yes, indeed. 

💭 This PR makes me think... we probably want to advertise a policy about breaking changes in VRL. In this case we are fixing a panic at the cost of requiring users to usage of `to_unix_timestamp` their VRL scripts. IMO this is worth the effort. 

In the future, we could do something like:
* in release X+1 we announce our intention to change behavior
* release X+2 we actually include the change 

On the other hand, this might be too much process for smaller changes.

P.S. This would be a non-breaking change if we finally got to introducing a non-strict mode.

Comment (jszwedko) [reply changelog.d/979.fix.md]: Agreed, it'd be nice to have a VRL deprecation process for riskier breaking changes that we aren't sure about to let users give us feedback. In this case I think it's ok to make the breaking change since the migration is simple (add a `!` to preserve the existing behavior).

**Review by jszwedko — APPROVED** [review]
