### PR TITLE
fix(stdlib): support hyphens in JIT parser

### LINKED ISSUE #998: Panic when match_datadog_query references key with hyphen
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

`match_datadog_query` cannot handle keys with hyphens in them. For example:
```
.custom."abc_def" = true
exists = match_datadog_query(., "_exists_:@abc_def") #works as expected, returns true

.custom."abc-def" = true
exists = match_datadog_query(., "_exists_:@abc-def") # panics, regardless of it key exists
```

### Configuration

```text
Reproducible from VRL REPL
```

### Version

vector 0.40.0 (x86_64-apple-darwin 1167aa9 2024-07-29 15:08:44.028365803)

### Debug Output

```text
thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vrl-0.17.0/src/stdlib/match_datadog_query.rs:418:42:
should parse value path (lookup_field): InvalidPathSyntax { path: "custom.abc-def" }
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: vrl::stdlib::match_datadog_query::lookup_field
   4: <vrl::stdlib::match_datadog_query::VrlFilter as vrl::datadog::filter::filter::Filter<vrl::value::value::Value>>::exists
   5: vrl::datadog::filter::matcher::build_matcher
   6: <vrl::stdlib::match_datadog_query::MatchDatadogQuery as vrl::compiler::function::Function>::compile
   7: vrl::compiler::compiler::Compiler::compile_function_call
   8: vrl::compiler::compiler::Compiler::compile_expr
   9: vrl::compiler::compile_with_state
  10: vrl::cli::repl::resolve
  11: <vrl::cli::repl::Repl as rustyline::validate::Validator>::validate
  12: rustyline::Editor<H,I>::readline_edit
  13: vrl::cli::cmd::run
  14: vrl::cli::cmd::cmd
  15: vector::cli::SubCommand::execute::{{closure}}
  16: vector::app::Application::prepare_from_opts
  17: vector::app::Application::run
  18: vector::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by Lou-Kamades**
closes: #998

### CODE REVIEW

File: src/path/jit.rs [hunk 1]
```diff
@@ -266,6 +266,8 @@ mod test {
                 ],
             ),
             (".foo", vec![BorrowedSegment::Field("foo".into())]),
+            (".a-b", vec![BorrowedSegment::Field("a-b".into())]),
+            (".-a-b", vec![BorrowedSegment::Invalid]),
```
Comment (pront) [inline src/path/jit.rs:270]: What happens if there is a trailing `-`?

**Review by pront — COMMENTED** [review]
Thank you @lou-kamades, this looks reasonable. I will take another look shortly. 

Also, left a comment on the original issue: https://github.com/vectordotdev/vrl/issues/998#issuecomment-2338459893. Even if we fix this, there's still a possibility of a panic.

File: src/path/jit.rs (hunk 1 above)
Comment (Lou-Kamades) [reply src/path/jit.rs:271]: It will parse correctly (I just added a test case for it). The leading hyphen case fails because the JitState is `EventRoot` for the first parsed char and this PR only adds hyphen support when JitState is `Field`.

I've come around to thinking it's better to add hyphen support for all `JitState` however, because that's more consistent. If a user truly wants to start a key with a hyphen, who am I to prevent it?

**Comment by pront** [comment]
Hey, apologies for the delay here. We had some internal discussions because this affects path parsing in general and not just DD search syntax. We are dealing with two different domains (VRL and DD search syntax) and although they happen to be similar, there are no strict guarantees. That being said, I think this PR has merit. I will take another look later today to ensure I didn't miss something.

**Comment by pront** [comment]
@Lou-Kamades: Please add a changelong entry.

**Comment by pront** [comment]
Can we also add a VRL test for a query that contains `-` in `lib/tests/tests/functions/match_datadog_query`?

**Comment by Lou-Kamades** [comment]
> Can we also add a VRL test for a query that contains `-` in `lib/tests/tests/functions/match_datadog_query`?

Just added! Thanks for pointing these tests out, I had no idea they existed

File: changelog.d/1025.fix.md [hunk 2]
```diff
@@ -0,0 +1 @@
+Adds support for hyphens in the JIT path parser: `JitValuePathIter.next()`
```
Comment (pront) [inline changelog.d/1025.fix.md:1]: I think we can remove this `: JitValuePathIter.next()`.

File: lib/tests/tests/functions/match_datadog_query.vrl [hunk 3]
```diff
@@ -0,0 +1,3 @@
+# result: true
+
+match_datadog_query({"a-b": 1}, "@a-b:1")
```
Comment (pront) [inline lib/tests/tests/functions/match_datadog_query.vrl:3]: nit: add newline

**Review by pront — APPROVED** [review]
Thanks @Lou-Kamades!
